### ISSUE TITLE
Create port(s) for Ada runtime

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit#102]

**Comment by jklmnn** [comment]
Generally, the runtime sources are available in the gcc port. But the runtime needs to be bootstrapped and cannot be compiled with the regular target (because gnatmake then needs a runtime).
I could compile single files with `gnatmake -a -c -x -gnatg -gnatp -gnatn2 <file>.ads`. The main difference is `-a` which tells gnatmake to consider all files, otherwise it won't compile single specifications without body.
Due to the difference of libraries and runtime and the limited ways to specify the runtime location we should rediscuss how we want to build the runtime support. I'm not sure how much of the runtime we can exclude to libraries.

**Comment by senier** [comment]
Yes, the linker should only include those files that are required. We could go for only one single runtime and see whether this has any disadvantages.

Regarding location of adalib: I don't understand the issue here. Why not install *.ads and *.ali files into some runtime directory (somewhere in var?) and point RTS to it?

**Comment by jklmnn** [comment]
Fixed with https://github.com/jklmnn/genode/commit/4672fd3eabc0fa264c99ae07cef14066a0349c69.
