### ISSUE TITLE
HTTP Filter design

### ISSUE THREAD

**Issue by senier** [Componolit/componolit#128]
The trusted component should not require a TCP/IP stack to monitor the traffic between web server and network. Hence, we rely on the simpler terminal session. A networking component connects the validator to the network and terminates potential TLS connections. Once a client connects from the network, the networking component creates a new terminal session with the validator. The validator, in turn, creates a new terminal session with the web service proxy, which establishes a new TCP connection to the web server (IP address and port of the webserver are configured statically). This maps incoming TCP connections to TCP connecitons of the web server while keeping the validator simple. No tracking of session needs to occur, accept matching request/reply with the right set of terminal client/server sessions.

![http_filter2](https://user-images.githubusercontent.com/6357197/40609747-e8ed3cae-626f-11e8-888d-ef0632df62c8.jpg)

**Comment by jklmnn** [comment]
To test this scenarion we could use the lighttpd port and the Aurora browser. There is already an example for this.
Also it would probably sufficient to create a single component that uses/provides a terminal session (depending on connection direction) and uses a nic session. The nic session doesn't necessarily need to be provided since this could be done by using the nic_bridge.

**Comment by senier** [comment]
Even a bit simple: The lighttpd scenario with the local browser (and qemu port forwarding). That works out of the box.

Which component are you referring to that wouldn't need a Nic session? Would this achieve our goal to have a simple component that only use two terminal sessions?

**Comment by jklmnn** [comment]
I was referring to the IP endpoints that also provide the terminal sessions. But I'm already not sure anymore if this idea would bring us anywhere.

I still struggle to get the connection between sockets and the Nic session into my mind.
The uplink isn't the problem here as (in my understanding) it would be sufficient to open a listening socket on a Nic client and get our IP address from the connected network.

But the connection to the web service is not fully clear to me. Do we provide a Nic session (which would e.g. work with the lighttpd port) and do our own DHCP (or static addressing) or do we use it (which we would do if we would connect to a VirtualBox iirc).
Also I do not see how we would connect a socket to the Nic session we provide. If a socket is opened the Nic session is automatically used so we still would use some kind of "gender changer".

**Comment by jklmnn** [comment]
Unfortunately my cheat using the timer does not work. So it seems we have to use a separate thread to check if something can be read.

**Comment by jklmnn** [comment]
With https://github.com/jklmnn/componolit/commit/9d85911e979abca1982c13b09d9f929540ca0c5e the filter is able to relay http traffic via a terminal session. Yet if more than one connection is allowed the component hangs after the first connection is terminated.

**Comment by jklmnn** [comment]
The hangup was fixed with https://github.com/jklmnn/componolit/commit/c670b1ac5ee160557df624547781090c1e47b86f.
